#!/usr/bin/env python3
"""One-shot cleanup script for the ``reports/`` directory.

This script deletes report directories and files that are no longer part of
the project's "latest standard" workflow — i.e. they are not referenced by
the current source, tests, CI, or ``docs/operations/`` runbooks.

Run ``python tools/reports/prune_expired_reports.py`` for a dry-run that lists
everything that *would* be deleted. Pass ``--apply`` to actually remove
the items. The script never touches:

* ``reports/.gitkeep`` (placeholder).
* Any directory or file that the most recent workflow still depends on
  (APC vs MTP benchmark, persona-campaigns/inference-ab-r*,
  persona-campaigns/vllm-audit-25seed-cohort-{a,b},
  persona-runtime/{game,study-*}, playtests/study-four-semester-20260803,
  repair-experiments/vllm-cohort-*, private-local-vllm/vllm-cohort-*).
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPORTS = ROOT / "reports"

# Top-level ``reports/<name>`` directories that are no longer needed.
EXPIRED_DIRS: tuple[str, ...] = (
    "balance",
    "boundary",
    "browse",
    "play",
    "validation",
    "fix-verify",
    "final-verify",
    "full-scenario-20260706",
    "candidate-localization-runtime",
    "candidate-localization-validation",
    "contract-game-runtime",
    "contract-smoke",
    "contract-smoke-2",
    "game-test-20260718",
    "local-game-runtime",
    "pretest-game-runtime",
    "interactive",
    "interactive-contract-smoke",
    "localization-baseline-fixed",
    "localization-baseline-fixed-final",
    "localization-baseline-holdout",
    "localization-baseline-holdout-final",
    "localization-candidate-fixed",
    "localization-candidate-fixed-final",
    "localization-candidate-holdout",
    "localization-candidate-holdout-final",
    "localization-final-validation",
    "localization-integrated-validation",
    "repair-sensitivity",
    "vllm-smoke-fixture",
)

# Loose files under ``reports/`` that are generated by other tools and safe to drop.
EXPIRED_FILES: tuple[str, ...] = (
    "index.html",
    "manifest.json",
    "localization-identity-candidate.patch",
    "localization-repair-decision.json",
)

# ``reports/persona-campaigns/<name>`` directories superseded by the
# ``inference-ab-r*`` runs (Aug 4). ``vllm-audit-25seed-cohort-{a,b}`` are
# retained because ``config/build_week_2026_target_vllm_{a,b}.json`` and
# ``src/game_analysis_agent/experiment_registry.py`` still depend on them.
# ``vllm-audit-25seed-cohort-c`` has no code/config reference and is dropped.
EXPIRED_CAMPAIGNS: tuple[str, ...] = (
    "openai-all-six-seed-42-20w",
    "openai-slacker-seed-42-20w",
    "openai-social-seed-42-20w",
    "vllm-money-seed-42-20w",
    "vllm-newbie-seed-42-20w",
    "vllm-audit-25seed-cohort-c",
)

# ``reports/persona-runtime/<name>`` directories superseded by ``game/`` and
# the latest study runs.
EXPIRED_PERSONA_RUNTIME_SUBDIRS: tuple[str, ...] = (
    "audit-25seed-game",
)

# ``reports/playtests/<name>`` subdirectories that must be preserved.
KEEP_PLAYTEST_SUBDIRS: frozenset[str] = frozenset(
    {"study-four-semester-20260803"}
)


@dataclass
class PendingDeletion:
    """One filesystem path the script intends to delete."""

    path: Path
    kind: str  # "dir" or "file"
    reason: str


def collect_pending() -> list[PendingDeletion]:
    """Build the list of paths the script would delete.

    Order matters: directories are listed before loose files at the same
    level, so the dry-run output mirrors what ``--apply`` removes.
    """

    pending: list[PendingDeletion] = []
    if not REPORTS.exists():
        return pending

    for name in EXPIRED_DIRS:
        path = REPORTS / name
        if path.exists():
            pending.append(
                PendingDeletion(path=path, kind="dir", reason=f"top-level {name}/ is expired")
            )

    for name in EXPIRED_FILES:
        path = REPORTS / name
        if path.exists():
            pending.append(
                PendingDeletion(path=path, kind="file", reason=f"top-level {name} is regenerated by tools")
            )

    campaigns_dir = REPORTS / "persona-campaigns"
    for name in EXPIRED_CAMPAIGNS:
        path = campaigns_dir / name
        if path.exists():
            pending.append(
                PendingDeletion(
                    path=path,
                    kind="dir",
                    reason=f"persona-campaign {name} superseded by inference-ab-r*",
                )
            )

    runtime_dir = REPORTS / "persona-runtime"
    for name in EXPIRED_PERSONA_RUNTIME_SUBDIRS:
        path = runtime_dir / name
        if path.exists():
            pending.append(
                PendingDeletion(
                    path=path,
                    kind="dir",
                    reason=f"persona-runtime {name} superseded by game/ and study-*",
                )
            )

    playtests_dir = REPORTS / "playtests"
    if playtests_dir.exists():
        for child in sorted(playtests_dir.iterdir()):
            if child.is_dir() and child.name not in KEEP_PLAYTEST_SUBDIRS:
                pending.append(
                    PendingDeletion(
                        path=child,
                        kind="dir",
                        reason=f"playtests/{child.name} not in KEEP_PLAYTEST_SUBDIRS",
                    )
                )

    return pending


def print_dry_run(pending: Iterable[PendingDeletion]) -> None:
    items = list(pending)
    if not items:
        print("No expired reports to remove. The directory already matches the latest standard.")
        return
    print(f"Would delete {len(items)} paths under {REPORTS}:")
    for entry in items:
        rel = entry.path.relative_to(ROOT)
        print(f"  [{entry.kind:>4}] {rel}    # {entry.reason}")


def apply_deletions(pending: Iterable[PendingDeletion]) -> int:
    removed = 0
    for entry in pending:
        if entry.kind == "dir":
            shutil.rmtree(entry.path)
        else:
            entry.path.unlink()
        removed += 1
    return removed


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete the listed paths. Default is a dry-run that only prints.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit the pending deletion list as JSON (one object per line).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    pending = collect_pending()

    if args.json:
        for entry in pending:
            print(
                json.dumps(
                    {
                        "path": str(entry.path.relative_to(ROOT)),
                        "kind": entry.kind,
                        "reason": entry.reason,
                    }
                )
            )
        if not args.apply:
            return 0

    if not args.apply:
        print_dry_run(pending)
        return 0

    print_dry_run(pending)
    removed = apply_deletions(pending)
    print(f"Removed {removed} path(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
